# Generated by Django 4.1.5 on 2023-02-06 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, verbose_name="title of item in store"
                    ),
                ),
                (
                    "price",
                    models.FloatField(
                        default=0.0, verbose_name="price of item in store"
                    ),
                ),
                (
                    "discount",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="discount price of item in store",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("S", "shirt"),
                            ("SW", "sport wear"),
                            ("OW", "outwear"),
                        ],
                        default="S",
                        max_length=2,
                        verbose_name="category of item in store",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        choices=[
                            ("E", "eco"),
                            ("B", "bestSeller"),
                            ("N", "new"),
                            ("D", "discount"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="label of item in store",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default="new_product", verbose_name="slug of item in store"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Incidunt sapiente temporibus nobis non mollitia dolore, culpa nostrum tenetur veniam facilis doloremque, culpa reprehenderit praesentium excepturi nostrum earum fugit sit laboriosam pariatur, assumenda sequi incidunt quibusdam, amet quis et libero cupiditate itaque autem earum laudantium. Similique tempore veniam illo obcaecati ea labore illum provident perspiciatis corrupti quae, alias pariatur cumque delectus nemo maiores eius aperiam eligendi? Perferendis omnis consectetur deserunt dolorem accusantium quia tenetur voluptates earum molestias quis, iusto porro ducimus voluptates vel recusandae nihil blanditiis quasi tenetur nesciunt hic, cupiditate modi natus, illum praesentium aliquid id labore molestias libero, corporis quam fugiat nemo amet temporibus aliquid laborum? Similique eligendi minus molestias at quibusdam qui rem iste facilis incidunt, porro neque molestias consectetur, quis ipsa fugiat incidunt tempore dolorum ratione consequatur, asperiores possimus autem quam quaerat quia rerum expedita incidunt suscipit?",
                        verbose_name="description of item in store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordered",
                    models.BooleanField(
                        default=False,
                        verbose_name="checked if item is inside the order",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1, verbose_name="quantity of item in cart"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.item",
                        verbose_name="item selected in the store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user who added the item the order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="moment the order was created"
                    ),
                ),
                (
                    "ordered_date",
                    models.DateTimeField(
                        verbose_name="moment the order is checked out"
                    ),
                ),
                (
                    "ordered",
                    models.BooleanField(
                        default=False,
                        verbose_name="checked if order is completed and checked out",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        to="core.orderitem", verbose_name="items added to cart"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user who created the order",
                    ),
                ),
            ],
        ),
    ]
