# Generated by Django 4.1.5 on 2023-02-07 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(
                default="Quae vel molestiae nostrum numquam quam consectetur nemo eaque libero quaerat, vel nihil fugit iusto quas illum perferendis dolorem quo rerum ipsum, eum nulla pariatur hic cum provident impedit, veritatis ab maxime aliquid inventore accusantium iste excepturi porro ex? Molestiae aperiam esse eos iste error eius dicta soluta officia rem dolor, in dignissimos ab distinctio rem quis eligendi id obcaecati, maiores repellendus dicta labore debitis sequi quaerat ad fugit ipsum, est dicta eos iusto perferendis quidem a tempore, reiciendis in culpa libero alias eos inventore perferendis repellat temporibus? Excepturi eligendi illum ut unde doloremque enim consectetur eos fuga, dolore soluta quas laudantium animi aspernatur tempora atque praesentium voluptatum, fugit possimus delectus quo nobis beatae totam rerum itaque at eveniet, cum praesentium iusto amet omnis quae? Quibusdam beatae similique accusantium quos est perspiciatis in animi laboriosam sint totam, aspernatur iure veniam molestias doloribus nihil ullam nesciunt eius ipsa facilis quia, minima voluptate animi temporibus voluptatibus labore ipsam, eligendi saepe non deserunt architecto dolores earum, beatae reiciendis quia earum quae quo architecto cumque alias.",
                verbose_name="description of item in store",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="ordered",
            field=models.BooleanField(
                default=False,
                verbose_name="checked if item is part of an order that is checked out",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user who added the item the order",
            ),
        ),
    ]
