# Generated by Django 4.1.5 on 2023-02-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_item_description_alter_orderitem_ordered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(
                default="Ipsum sit neque iusto, unde aut assumenda molestiae error quo qui, quaerat excepturi numquam dicta officiis quo fugiat? Doloribus iusto doloremque atque dolore harum architecto culpa dolores velit eligendi provident, aut consectetur a quo enim eaque incidunt eos, error placeat eaque id veniam nihil deleniti at quisquam eveniet earum, iste rem minus dignissimos commodi maiores? Quo aspernatur sit aliquid officia eveniet numquam consectetur tempora qui, non deserunt eius quis ex ducimus velit quia voluptates debitis, odit ducimus fugiat consequatur sunt ex minus ipsum? Maiores iure aliquid quam quaerat dignissimos, facilis est ipsum molestias iure atque magni distinctio officiis neque qui placeat, et quo sequi veniam esse minus harum provident inventore magni tempore, velit vero minima dolor a ut, omnis ad autem.",
                verbose_name="description of item in store",
            ),
        ),
    ]
